### ISSUE TITLE
Update needed for patch 4.6

### ISSUE THREAD

**Issue by Epikest** [sefinek24/Genshin-Impact-ReShade#43]

**Comment by sefinek24** [comment]
What specifically needs to be updated?

**Comment by Epikest** [comment]
> What specifically needs to be updated?

FPS Unlocker somehow feels "less smooth". the displayed fps appears without a cap but in-game it feels like 60 FPS.

**Comment by Epikest** [comment]
the game crashes if you close it from the menu, could be related to this.

**Comment by sefinek24** [comment]
No one has reported similar issues to me. Personally, I haven't checked the Stella Mod in GI 4.6 yet. Only Stella Mod Plus subscribers have the stable version.

**Comment by Epikest** [comment]
> No one has reported similar issues to me. Personally, I haven't checked the Stella Mod in GI 4.6 yet. Only [Stella Mod Plus](https://sefinek.net/genshin-impact-reshade/subscription) subscribers have the stable version.

can i have access to try it out then?

**Comment by sefinek24** [comment]
Honestly, I haven't done anything for a month with the FPS unlocker (see https://github.com/sefinek24/Genshin-FPS-Unlocker).

I probably won't give you access to the newer version because of security reasons. The newer versions have a security system that hasn't been thoroughly tested yet, and I simply don't want any damage on the API side.

**Comment by Epikest** [comment]
alright
